<?xml version="1.0"?>
<robot name="garbage-bytes" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- gazebo plugins -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
            <legacyModeNS>false</legacyModeNS>
        </plugin>
    </gazebo>

    <xacro:include filename="$(find br-description)/urdf/macros.xacro" />

    <link name="base_link"/>

    <!-- Add chassis and inertial link -->
    <link name="chassis">
        <interial>
            <xacro:chassis_inertial_params/>
        </interial>
        <visual>
            <xacro:chassis_geometry/>
        </visual>
        <collision>
            <xacro:chassis_geometry/>
        </collision>
    </link>

    <joint name="base_link_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="chassis"/>
    </joint>

    <!-- Head servo joint and transmission -->
    <link name="head">
        <visual>
            <xacro:head_geometry/>
        </visual>
        <collision>
            <xacro:head_geometry/>
        </collision>
        <inertial>
            <xacro:head_inertial_params/>
        </inertial>
    </link>
    <joint name="head_joint" type="revolute">
        <origin xyz="-0.230 0.00 0.7" rpy="0 0 0"/>
        <parent link="chassis" />
        <child link="head" />
        <axis xyz="0 1 0" />
        <limit upper="0.4" lower="-0.4" effort="1" velocity="10"/>
    </joint>
    <transmission name="head_transmission" type="SimpleTransmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="head_joint">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="head_motor">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <!-- Add left and right wheels -->
    <link name="left_wheel">
        <inertial>
            <xacro:wheel_inertial_params />
        </inertial>
        <visual>
            <xacro:wheel_geometry />
            <material name="black" />
        </visual>
        <collision>
            <xacro:wheel_geometry />
        </collision>
    </link>

    <joint name="left_wheel_joint" type="continuous">
        <origin xyz="${wheel_offset} ${base_length/2 + wheel_base_separation + wheel_thickness/2} 0" rpy="1.5708 0 0" />
        <parent link="chassis" />
        <child link="left_wheel" />
        <axis xyz="0 0 -1" />
        <limit effort="10" velocity="100" />
    </joint>

    <xacro:wheel_transmission name="left_wheel" />

    <link name="right_wheel">
        <inertial>
            <xacro:wheel_inertial_params />
        </inertial>
        <visual>
            <xacro:wheel_geometry />
            <material name="black" />
        </visual>
        <collision>
            <xacro:wheel_geometry />
        </collision>
    </link>

    <joint name="right_wheel_joint" type="continuous">
        <origin xyz="${wheel_offset} ${-1*(base_length/2 + wheel_base_separation + wheel_thickness/2)} 0" rpy="1.5708 0 0" />
        <parent link="chassis" />
        <child link="right_wheel" />
        <axis xyz="0 0 -1" />
        <limit effort="10" velocity="100" />
    </joint>

    <xacro:wheel_transmission name="right_wheel" />

    <!-- Add front and back casters -->
    <link name="front_caster">
        <inertial>
            <xacro:caster_inertial_params />
        </inertial>
        <visual>
            <xacro:caster_geometry />
            <material name="grey" />
        </visual>
        <collision>
            <xacro:caster_geometry />
        </collision>
    </link>

    <joint name="front_caster_joint" type="fixed">
        <origin xyz="${base_width/2 - caster_radius - caster_offset} 0 ${vertical_wheel_offset + caster_radius - wheel_radius}" rpy="0 0 0" />
        <parent link="chassis" />
        <child link="front_caster" />
    </joint>

    <!-- Add the trash can -->
    <link name="trash_can">
        <visual>
            <geometry>
                <mesh filename="package://br-description/meshes/trash_can.stl" scale="0.00075 0.00075 0.00075"/>
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://br-description/meshes/trash_can.stl" scale="0.00075 0.00075 0.00075"/>
            </geometry>
        </collision>
    </link>

    <joint name="trash_can_joint" type="fixed">
        <origin xyz="0 0 ${base_thickness/2 + 0.001}" rpy="1.5708 0 1.5708" />
        <parent link="chassis" />
        <child link="trash_can" />
    </joint>

    <xacro:dist_sensor name="front" x="${base_width/2 + 0.01}" y="0" z="${base_thickness/2 - 0.02}" r="0" p="0" yaw="0"/>
    <xacro:dist_sensor name="left" x="${base_width/2 + 0.01}" y="0.1" z="${base_thickness/2 - 0.02}" r="0" p="0" yaw="0.785398"/>
    <xacro:dist_sensor name="right" x="${base_width/2 + 0.01}" y="-0.1" z="${base_thickness/2 - 0.02}" r="0" p="0" yaw="-0.785398"/>
    <xacro:dist_sensor name="rear" x="${-1*(base_width/2 + 0.01)}" y="0" z="${base_thickness/2 - 0.02}" r="0" p="0" yaw="3.14159"/>
    <xacro:dist_sensor name="bottom" x="${base_width/2 + 0.01}" y="0" z="0" r="0" p="1.5708" yaw="0"/>

    <!-- IMU -->
    <link name="imu_link">
        <visual>
            <geometry>
                <box size="0.001 0.002 0.0005" />
            </geometry>
            <material name="black" />
        </visual>
    </link>
    <joint name="chassis_imu_joint" type="fixed">
        <origin xyz="-0.230 0.00 0.45" rpy="0 0 0" />
        <parent link="chassis" />
        <child link="imu_link" />
    </joint>
    <gazebo reference="imu_link">
        <gravity>false</gravity>
        <sensor name="imu_sensor" type="imu">
            <always_on>true</always_on>
            <update_rate>30</update_rate>
            <visualize>true</visualize>
            <topic>__default_topic__</topic>
            <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
                <topicName>/imu/data</topicName>
                <bodyName>imu_link</bodyName>
                <updateRateHZ>60.0</updateRateHZ>
                <gaussianNoise>0.001</gaussianNoise>
                <xyzOffset>0 0 0</xyzOffset>
                <rpyOffset>0 0 0</rpyOffset>
                <frameName>imu_link</frameName>
            </plugin>
            <pose>0 0 0 0 0 0</pose>
        </sensor>
   </gazebo>

    <!-- GPS -->
    <link name="gps_link">
        <visual>
            <geometry>
                <box size="0.01 0.02 0.005" />
            </geometry>
            <material name="black" />
        </visual>
    </link>
    <joint name="chassis_gps_joint" type="fixed">
        <origin xyz="-0.05 0.0 0.0825" rpy="0 0 0" />
        <parent link="head" />
        <child link="gps_link" />
    </joint>
    <gazebo>
        <plugin name="gps_controller" filename="libhector_gazebo_ros_gps.so">
            <updateRate>10.0</updateRate>
            <bodyName>base_link</bodyName>
            <frameId>gps_link</frameId>
            <topicName>/gps</topicName>
            <referenceLatitude>38.5853618</referenceLatitude>
            <referenceLongitude>-121.3594389</referenceLongitude>
            <velocityTopicName>/gps/ignore</velocityTopicName>
            <drift>5.0 5.0 5.0</drift>
            <gaussianNoise>0.1 0.1 0.1</gaussianNoise>
            <velocityDrift>0 0 0</velocityDrift>
            <velocityGaussianNoise>0.1 0.1 0.1</velocityGaussianNoise>
        </plugin>
        <material>Gazebo/Grey</material>
    </gazebo>

    <!-- Main camera -->
    <xacro:camera_sensor name="camera" x="${head_width/2}" y="${head_length/2-0.06}" z="0" r="0" p="0" yaw="0"/>

    <!-- Training cameras -->
    <xacro:camera_sensor name="camera_l" x="${head_width/2}" y="${head_length/2+0.06}" z="0" r="0" p="0" yaw="0.78539816339"/>
    <xacro:camera_sensor name="camera_r" x="${head_width/2}" y="${-1*(head_length/2+0.06)}" z="0" r="0" p="0" yaw="-0.78539816339"/>


</robot>
