#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'br-detection','console_scripts','detection_node'
__requires__ = 'br-detection'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('br-detection', 'console_scripts', 'detection_node')()
    )
