// Generated by gencpp from file br_behavior_engine/StringList.msg
// DO NOT EDIT!


#ifndef BR_BEHAVIOR_ENGINE_MESSAGE_STRINGLIST_H
#define BR_BEHAVIOR_ENGINE_MESSAGE_STRINGLIST_H

#include <ros/service_traits.h>


#include <br_behavior_engine/StringListRequest.h>
#include <br_behavior_engine/StringListResponse.h>


namespace br_behavior_engine
{

struct StringList
{

typedef StringListRequest Request;
typedef StringListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StringList
} // namespace br_behavior_engine


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::br_behavior_engine::StringList > {
  static const char* value()
  {
    return "cce5a364f3a3be12c9722c6dcad2fa94";
  }

  static const char* value(const ::br_behavior_engine::StringList&) { return value(); }
};

template<>
struct DataType< ::br_behavior_engine::StringList > {
  static const char* value()
  {
    return "br_behavior_engine/StringList";
  }

  static const char* value(const ::br_behavior_engine::StringList&) { return value(); }
};


// service_traits::MD5Sum< ::br_behavior_engine::StringListRequest> should match
// service_traits::MD5Sum< ::br_behavior_engine::StringList >
template<>
struct MD5Sum< ::br_behavior_engine::StringListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::br_behavior_engine::StringList >::value();
  }
  static const char* value(const ::br_behavior_engine::StringListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::br_behavior_engine::StringListRequest> should match
// service_traits::DataType< ::br_behavior_engine::StringList >
template<>
struct DataType< ::br_behavior_engine::StringListRequest>
{
  static const char* value()
  {
    return DataType< ::br_behavior_engine::StringList >::value();
  }
  static const char* value(const ::br_behavior_engine::StringListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::br_behavior_engine::StringListResponse> should match
// service_traits::MD5Sum< ::br_behavior_engine::StringList >
template<>
struct MD5Sum< ::br_behavior_engine::StringListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::br_behavior_engine::StringList >::value();
  }
  static const char* value(const ::br_behavior_engine::StringListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::br_behavior_engine::StringListResponse> should match
// service_traits::DataType< ::br_behavior_engine::StringList >
template<>
struct DataType< ::br_behavior_engine::StringListResponse>
{
  static const char* value()
  {
    return DataType< ::br_behavior_engine::StringList >::value();
  }
  static const char* value(const ::br_behavior_engine::StringListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BR_BEHAVIOR_ENGINE_MESSAGE_STRINGLIST_H
